description: >
  Validate Renovate self-hosted configuration file.

  Self-hosted configuration file docs: https://github.com/renovatebot/renovate/blob/master/docs/usage/self-hosting.md#user-content-configuration

executor:
  name: default
  tag: "\
    <<# parameters.renovate_version >>\
    << parameters.renovate_version >>-slim\
    <</ parameters.renovate_version >>\
    <<^ parameters.renovate_version >>\
    slim\
    <</ parameters.renovate_version >>\
    "

resource_class: <<parameters.resource_class>>

parameters:
  renovate_version:
    type: string
    description: The version of your self-hosted instance of Renovate.
  resource_class:
    type: string
    default: medium
    description: Amount of CPU and RAM allocated to each container in a job.
  self_hosted_config_file_path:
    type: string
    default: config.js
    description: Path to self-hosted configuration file.

steps:
  - checkout
  - run:
      name: Validate Renovate self-hosted config
      command: renovate-config-validator
      environment:
        RENOVATE_CONFIG_FILE: << parameters.self_hosted_config_file_path >>
