description: >
  Docker image for Renovate CLI
docker:
  - image: 'renovate/renovate:<<parameters.tag>>'
parameters:
  tag:
    default: latest
    description: |
      Pick a specific renovate/renovate image variant:
      https://hub.docker.com/r/renovate/renovate/tags
      Use the "slim" tag if you only use package managers that don't need third party binaries (e.g. JS, Docker, Nuget, pip)
    type: string
