description: |
  Validate Renovate configuration file and self-hosted configuration file.

  Configuration file definition: https://docs.renovatebot.com/configuration-options/
  Self-hosted configuration file docs: https://github.com/renovatebot/renovate/blob/master/docs/usage/self-hosting.md#user-content-configuration

usage:
  version: 2.1
  orbs:
    renovate: daniel-shuy/renovate@x.y
  workflows:
    lint:
      jobs:
        - renovate/validate-config:
            self_hosted_config_file_path: renovate.config.js
