description: |
  Validate Renovate self-hosted configuration file.

  Self-hosted configuration file docs: https://github.com/renovatebot/renovate/blob/master/docs/usage/self-hosting.md#user-content-configuration

  Override self_hosted_config_file_path if the self-hosted configuration file is not at the default path (config.js).

usage:
  version: 2.1
  orbs:
    renovate: daniel-shuy/renovate@x.y
  workflows:
    lint:
      jobs:
        - renovate/validate-self-hosted-config:
            renovate_version: $RENOVATE_VERSION
            self_hosted_config_file_path: renovate.config.js
